// flow-typed signature: b37b0af96b0dc8034d59fbb697f1ce65
// flow-typed version: <<STUB>>/assets-webpack-plugin_v^3.4.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'assets-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'assets-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'assets-webpack-plugin/lib/getAssetKind' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/lib/getFileExtension' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/lib/isHMRUpdate' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/lib/isSourceMap' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/lib/output/createOutputWriter' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/lib/output/createQueuedWriter' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/lib/pathTemplate' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/lib/utils/error' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/test/fixtures/common-chunks/common' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/test/fixtures/common-chunks/one' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/test/fixtures/common-chunks/two' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/test/fixtures/manifest' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/test/fixtures/manifestWithSourceMap' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/test/fixtures/one' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/test/fixtures/styles' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/test/fixtures/two' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/test/getAssetKind.test' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/test/getFileExt.test' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/test/index.test' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/test/isHMRUpdate.test' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/test/isSourceMap.test' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/test/multiCompiler.test' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/test/pathTemplate.test' {
  declare module.exports: any;
}

declare module 'assets-webpack-plugin/test/utils/expectOutput' {
  declare module.exports: any;
}

// Filename aliases
declare module 'assets-webpack-plugin/index' {
  declare module.exports: $Exports<'assets-webpack-plugin'>;
}
declare module 'assets-webpack-plugin/index.js' {
  declare module.exports: $Exports<'assets-webpack-plugin'>;
}
declare module 'assets-webpack-plugin/lib/getAssetKind.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/lib/getAssetKind'>;
}
declare module 'assets-webpack-plugin/lib/getFileExtension.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/lib/getFileExtension'>;
}
declare module 'assets-webpack-plugin/lib/isHMRUpdate.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/lib/isHMRUpdate'>;
}
declare module 'assets-webpack-plugin/lib/isSourceMap.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/lib/isSourceMap'>;
}
declare module 'assets-webpack-plugin/lib/output/createOutputWriter.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/lib/output/createOutputWriter'>;
}
declare module 'assets-webpack-plugin/lib/output/createQueuedWriter.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/lib/output/createQueuedWriter'>;
}
declare module 'assets-webpack-plugin/lib/pathTemplate.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/lib/pathTemplate'>;
}
declare module 'assets-webpack-plugin/lib/utils/error.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/lib/utils/error'>;
}
declare module 'assets-webpack-plugin/test/fixtures/common-chunks/common.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/test/fixtures/common-chunks/common'>;
}
declare module 'assets-webpack-plugin/test/fixtures/common-chunks/one.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/test/fixtures/common-chunks/one'>;
}
declare module 'assets-webpack-plugin/test/fixtures/common-chunks/two.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/test/fixtures/common-chunks/two'>;
}
declare module 'assets-webpack-plugin/test/fixtures/manifest.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/test/fixtures/manifest'>;
}
declare module 'assets-webpack-plugin/test/fixtures/manifestWithSourceMap.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/test/fixtures/manifestWithSourceMap'>;
}
declare module 'assets-webpack-plugin/test/fixtures/one.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/test/fixtures/one'>;
}
declare module 'assets-webpack-plugin/test/fixtures/styles.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/test/fixtures/styles'>;
}
declare module 'assets-webpack-plugin/test/fixtures/two.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/test/fixtures/two'>;
}
declare module 'assets-webpack-plugin/test/getAssetKind.test.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/test/getAssetKind.test'>;
}
declare module 'assets-webpack-plugin/test/getFileExt.test.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/test/getFileExt.test'>;
}
declare module 'assets-webpack-plugin/test/index.test.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/test/index.test'>;
}
declare module 'assets-webpack-plugin/test/isHMRUpdate.test.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/test/isHMRUpdate.test'>;
}
declare module 'assets-webpack-plugin/test/isSourceMap.test.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/test/isSourceMap.test'>;
}
declare module 'assets-webpack-plugin/test/multiCompiler.test.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/test/multiCompiler.test'>;
}
declare module 'assets-webpack-plugin/test/pathTemplate.test.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/test/pathTemplate.test'>;
}
declare module 'assets-webpack-plugin/test/utils/expectOutput.js' {
  declare module.exports: $Exports<'assets-webpack-plugin/test/utils/expectOutput'>;
}
