// flow-typed signature: f7eed962ef1ec7d1b728b5e8a055fc3a
// flow-typed version: <<STUB>>/autosize_v^3.0.17/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'autosize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'autosize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'autosize/dist/autosize' {
  declare module.exports: any;
}

declare module 'autosize/dist/autosize.min' {
  declare module.exports: any;
}

declare module 'autosize/src/autosize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'autosize/dist/autosize.js' {
  declare module.exports: $Exports<'autosize/dist/autosize'>;
}
declare module 'autosize/dist/autosize.min.js' {
  declare module.exports: $Exports<'autosize/dist/autosize.min'>;
}
declare module 'autosize/src/autosize.js' {
  declare module.exports: $Exports<'autosize/src/autosize'>;
}
