// flow-typed signature: b0a4282494ab3574f0bdbfc2ed8b3a4f
// flow-typed version: <<STUB>>/babel-plugin-react-pure-components_v^2.2.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-pure-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-pure-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-react-pure-components/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/fixtures/impure-instance-props/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/fixtures/impure-instance-props/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/fixtures/impure-methods/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/fixtures/impure-methods/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/fixtures/impure-ref/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/fixtures/impure-ref/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/fixtures/impure-state/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/fixtures/impure-state/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/fixtures/impure-static-props/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/fixtures/impure-static-props/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/fixtures/pure-class-expression/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/fixtures/pure-class-expression/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/fixtures/pure-no-props/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/fixtures/pure-no-props/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/fixtures/pure-props/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/fixtures/pure-props/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/fixtures/pure-static-props/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/fixtures/pure-static-props/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-pure-components/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-react-pure-components/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/lib/index'>;
}
declare module 'babel-plugin-react-pure-components/test/fixtures/impure-instance-props/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/fixtures/impure-instance-props/actual'>;
}
declare module 'babel-plugin-react-pure-components/test/fixtures/impure-instance-props/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/fixtures/impure-instance-props/expected'>;
}
declare module 'babel-plugin-react-pure-components/test/fixtures/impure-methods/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/fixtures/impure-methods/actual'>;
}
declare module 'babel-plugin-react-pure-components/test/fixtures/impure-methods/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/fixtures/impure-methods/expected'>;
}
declare module 'babel-plugin-react-pure-components/test/fixtures/impure-ref/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/fixtures/impure-ref/actual'>;
}
declare module 'babel-plugin-react-pure-components/test/fixtures/impure-ref/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/fixtures/impure-ref/expected'>;
}
declare module 'babel-plugin-react-pure-components/test/fixtures/impure-state/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/fixtures/impure-state/actual'>;
}
declare module 'babel-plugin-react-pure-components/test/fixtures/impure-state/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/fixtures/impure-state/expected'>;
}
declare module 'babel-plugin-react-pure-components/test/fixtures/impure-static-props/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/fixtures/impure-static-props/actual'>;
}
declare module 'babel-plugin-react-pure-components/test/fixtures/impure-static-props/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/fixtures/impure-static-props/expected'>;
}
declare module 'babel-plugin-react-pure-components/test/fixtures/pure-class-expression/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/fixtures/pure-class-expression/actual'>;
}
declare module 'babel-plugin-react-pure-components/test/fixtures/pure-class-expression/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/fixtures/pure-class-expression/expected'>;
}
declare module 'babel-plugin-react-pure-components/test/fixtures/pure-no-props/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/fixtures/pure-no-props/actual'>;
}
declare module 'babel-plugin-react-pure-components/test/fixtures/pure-no-props/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/fixtures/pure-no-props/expected'>;
}
declare module 'babel-plugin-react-pure-components/test/fixtures/pure-props/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/fixtures/pure-props/actual'>;
}
declare module 'babel-plugin-react-pure-components/test/fixtures/pure-props/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/fixtures/pure-props/expected'>;
}
declare module 'babel-plugin-react-pure-components/test/fixtures/pure-static-props/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/fixtures/pure-static-props/actual'>;
}
declare module 'babel-plugin-react-pure-components/test/fixtures/pure-static-props/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/fixtures/pure-static-props/expected'>;
}
declare module 'babel-plugin-react-pure-components/test/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-pure-components/test/index'>;
}
