// flow-typed signature: c9a903a793b7499bdb20aa040edfccce
// flow-typed version: <<STUB>>/basscss_v8.0.4/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'basscss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'basscss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'basscss/karma.conf' {
  declare module.exports: any;
}

declare module 'basscss/postcss.config' {
  declare module.exports: any;
}

declare module 'basscss/test/align.spec' {
  declare module.exports: any;
}

declare module 'basscss/test/border.spec' {
  declare module.exports: any;
}

declare module 'basscss/test/flexbox.spec' {
  declare module.exports: any;
}

declare module 'basscss/test/grid.spec' {
  declare module.exports: any;
}

declare module 'basscss/test/hide.spec' {
  declare module.exports: any;
}

declare module 'basscss/test/index' {
  declare module.exports: any;
}

declare module 'basscss/test/layout.spec' {
  declare module.exports: any;
}

declare module 'basscss/test/margin.spec' {
  declare module.exports: any;
}

declare module 'basscss/test/padding.spec' {
  declare module.exports: any;
}

declare module 'basscss/test/position.spec' {
  declare module.exports: any;
}

declare module 'basscss/test/test' {
  declare module.exports: any;
}

declare module 'basscss/test/type-scale.spec' {
  declare module.exports: any;
}

declare module 'basscss/test/typography.spec' {
  declare module.exports: any;
}

declare module 'basscss/test/util/add-element' {
  declare module.exports: any;
}

// Filename aliases
declare module 'basscss/karma.conf.js' {
  declare module.exports: $Exports<'basscss/karma.conf'>;
}
declare module 'basscss/postcss.config.js' {
  declare module.exports: $Exports<'basscss/postcss.config'>;
}
declare module 'basscss/test/align.spec.js' {
  declare module.exports: $Exports<'basscss/test/align.spec'>;
}
declare module 'basscss/test/border.spec.js' {
  declare module.exports: $Exports<'basscss/test/border.spec'>;
}
declare module 'basscss/test/flexbox.spec.js' {
  declare module.exports: $Exports<'basscss/test/flexbox.spec'>;
}
declare module 'basscss/test/grid.spec.js' {
  declare module.exports: $Exports<'basscss/test/grid.spec'>;
}
declare module 'basscss/test/hide.spec.js' {
  declare module.exports: $Exports<'basscss/test/hide.spec'>;
}
declare module 'basscss/test/index.js' {
  declare module.exports: $Exports<'basscss/test/index'>;
}
declare module 'basscss/test/layout.spec.js' {
  declare module.exports: $Exports<'basscss/test/layout.spec'>;
}
declare module 'basscss/test/margin.spec.js' {
  declare module.exports: $Exports<'basscss/test/margin.spec'>;
}
declare module 'basscss/test/padding.spec.js' {
  declare module.exports: $Exports<'basscss/test/padding.spec'>;
}
declare module 'basscss/test/position.spec.js' {
  declare module.exports: $Exports<'basscss/test/position.spec'>;
}
declare module 'basscss/test/test.js' {
  declare module.exports: $Exports<'basscss/test/test'>;
}
declare module 'basscss/test/type-scale.spec.js' {
  declare module.exports: $Exports<'basscss/test/type-scale.spec'>;
}
declare module 'basscss/test/typography.spec.js' {
  declare module.exports: $Exports<'basscss/test/typography.spec'>;
}
declare module 'basscss/test/util/add-element.js' {
  declare module.exports: $Exports<'basscss/test/util/add-element'>;
}
