// flow-typed signature: fbf2542ff1b8c15887f383ab986a5e9f
// flow-typed version: <<STUB>>/buffer-crc32_v^0.2.13/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buffer-crc32'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buffer-crc32' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'buffer-crc32/index' {
  declare module.exports: $Exports<'buffer-crc32'>;
}
declare module 'buffer-crc32/index.js' {
  declare module.exports: $Exports<'buffer-crc32'>;
}
