// flow-typed signature: 3bcf59f3f96070ce5efa705b4098fdcb
// flow-typed version: <<STUB>>/bugsnag-js_v^3.0.4/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bugsnag-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bugsnag-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bugsnag-js/dist/bugsnag.min' {
  declare module.exports: any;
}

declare module 'bugsnag-js/src/bugsnag' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bugsnag-js/dist/bugsnag.min.js' {
  declare module.exports: $Exports<'bugsnag-js/dist/bugsnag.min'>;
}
declare module 'bugsnag-js/src/bugsnag.js' {
  declare module.exports: $Exports<'bugsnag-js/src/bugsnag'>;
}
