// flow-typed signature: 228a361b0358b31547c2f6159d8a8ea9
// flow-typed version: <<STUB>>/bugsnag-js_v^4.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bugsnag-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bugsnag-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bugsnag-js/base/breadcrumb' {
  declare module.exports: any;
}

declare module 'bugsnag-js/base/client' {
  declare module.exports: any;
}

declare module 'bugsnag-js/base/config' {
  declare module.exports: any;
}

declare module 'bugsnag-js/base/lib/es-utils' {
  declare module.exports: any;
}

declare module 'bugsnag-js/base/lib/has-stack' {
  declare module.exports: any;
}

declare module 'bugsnag-js/base/lib/infer-release-stage' {
  declare module.exports: any;
}

declare module 'bugsnag-js/base/lib/positive-int-check' {
  declare module.exports: any;
}

declare module 'bugsnag-js/base/lib/test/es-utils.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/base/plugins/test/throttle.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/base/plugins/throttle' {
  declare module.exports: any;
}

declare module 'bugsnag-js/base/report' {
  declare module.exports: any;
}

declare module 'bugsnag-js/base/session' {
  declare module.exports: any;
}

declare module 'bugsnag-js/base/test/breadcrumb.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/base/test/client.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/base/test/config.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/base/test/report.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/base/test/session.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/config' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/index' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/console-breadcrumbs' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/context' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/device' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/inline-script-content' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/interaction-breadcrumbs' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/navigation-breadcrumbs' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/request' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/sessions' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/test/console-breadcrumbs.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/test/context.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/test/device.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/test/inline-script-content.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/test/interaction-breadcrumbs.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/test/navigation-breadcrumbs.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/test/request.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/test/sessions.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/test/unhandled-rejection.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/test/window-onerror.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/unhandled-rejection' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/plugins/window-onerror' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/test/client.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/test/fixtures/handled-error-object' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/test/fixtures/handled-error' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/test/fixtures/unhandled-error-global' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/test/fixtures/unhandled-error' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/test/lib/echo-server' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/test/lib/karma.conf' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/transports/lib/payload' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/transports/test/x-domain-request.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/transports/test/xml-http-request.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/transports/x-domain-request' {
  declare module.exports: any;
}

declare module 'bugsnag-js/browser/transports/xml-http-request' {
  declare module.exports: any;
}

declare module 'bugsnag-js/dist/bugsnag' {
  declare module.exports: any;
}

declare module 'bugsnag-js/dist/bugsnag.min' {
  declare module.exports: any;
}

declare module 'bugsnag-js/e2e/browserify/app' {
  declare module.exports: any;
}

declare module 'bugsnag-js/e2e/browserify/assertions.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/e2e/browserify/build' {
  declare module.exports: any;
}

declare module 'bugsnag-js/e2e/lib/karma.conf' {
  declare module.exports: any;
}

declare module 'bugsnag-js/e2e/lib/prepare' {
  declare module.exports: any;
}

declare module 'bugsnag-js/e2e/script/assertions.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/e2e/script/build' {
  declare module.exports: any;
}

declare module 'bugsnag-js/e2e/typescript/assertions.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/e2e/typescript/build' {
  declare module.exports: any;
}

declare module 'bugsnag-js/e2e/webpack/app' {
  declare module.exports: any;
}

declare module 'bugsnag-js/e2e/webpack/assertions.test' {
  declare module.exports: any;
}

declare module 'bugsnag-js/e2e/webpack/build' {
  declare module.exports: any;
}

declare module 'bugsnag-js/e2e/webpack/webpack.config' {
  declare module.exports: any;
}

declare module 'bugsnag-js/examples/js/app' {
  declare module.exports: any;
}

declare module 'bugsnag-js/examples/sourcemaps/app' {
  declare module.exports: any;
}

declare module 'bugsnag-js/node/index' {
  declare module.exports: any;
}

declare module 'bugsnag-js/types/test/fixtures/app' {
  declare module.exports: any;
}

declare module 'bugsnag-js/types/test/types.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bugsnag-js/base/breadcrumb.js' {
  declare module.exports: $Exports<'bugsnag-js/base/breadcrumb'>;
}
declare module 'bugsnag-js/base/client.js' {
  declare module.exports: $Exports<'bugsnag-js/base/client'>;
}
declare module 'bugsnag-js/base/config.js' {
  declare module.exports: $Exports<'bugsnag-js/base/config'>;
}
declare module 'bugsnag-js/base/lib/es-utils.js' {
  declare module.exports: $Exports<'bugsnag-js/base/lib/es-utils'>;
}
declare module 'bugsnag-js/base/lib/has-stack.js' {
  declare module.exports: $Exports<'bugsnag-js/base/lib/has-stack'>;
}
declare module 'bugsnag-js/base/lib/infer-release-stage.js' {
  declare module.exports: $Exports<'bugsnag-js/base/lib/infer-release-stage'>;
}
declare module 'bugsnag-js/base/lib/positive-int-check.js' {
  declare module.exports: $Exports<'bugsnag-js/base/lib/positive-int-check'>;
}
declare module 'bugsnag-js/base/lib/test/es-utils.test.js' {
  declare module.exports: $Exports<'bugsnag-js/base/lib/test/es-utils.test'>;
}
declare module 'bugsnag-js/base/plugins/test/throttle.test.js' {
  declare module.exports: $Exports<'bugsnag-js/base/plugins/test/throttle.test'>;
}
declare module 'bugsnag-js/base/plugins/throttle.js' {
  declare module.exports: $Exports<'bugsnag-js/base/plugins/throttle'>;
}
declare module 'bugsnag-js/base/report.js' {
  declare module.exports: $Exports<'bugsnag-js/base/report'>;
}
declare module 'bugsnag-js/base/session.js' {
  declare module.exports: $Exports<'bugsnag-js/base/session'>;
}
declare module 'bugsnag-js/base/test/breadcrumb.test.js' {
  declare module.exports: $Exports<'bugsnag-js/base/test/breadcrumb.test'>;
}
declare module 'bugsnag-js/base/test/client.test.js' {
  declare module.exports: $Exports<'bugsnag-js/base/test/client.test'>;
}
declare module 'bugsnag-js/base/test/config.test.js' {
  declare module.exports: $Exports<'bugsnag-js/base/test/config.test'>;
}
declare module 'bugsnag-js/base/test/report.test.js' {
  declare module.exports: $Exports<'bugsnag-js/base/test/report.test'>;
}
declare module 'bugsnag-js/base/test/session.test.js' {
  declare module.exports: $Exports<'bugsnag-js/base/test/session.test'>;
}
declare module 'bugsnag-js/browser/config.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/config'>;
}
declare module 'bugsnag-js/browser/index.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/index'>;
}
declare module 'bugsnag-js/browser/plugins/console-breadcrumbs.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/console-breadcrumbs'>;
}
declare module 'bugsnag-js/browser/plugins/context.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/context'>;
}
declare module 'bugsnag-js/browser/plugins/device.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/device'>;
}
declare module 'bugsnag-js/browser/plugins/inline-script-content.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/inline-script-content'>;
}
declare module 'bugsnag-js/browser/plugins/interaction-breadcrumbs.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/interaction-breadcrumbs'>;
}
declare module 'bugsnag-js/browser/plugins/navigation-breadcrumbs.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/navigation-breadcrumbs'>;
}
declare module 'bugsnag-js/browser/plugins/request.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/request'>;
}
declare module 'bugsnag-js/browser/plugins/sessions.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/sessions'>;
}
declare module 'bugsnag-js/browser/plugins/test/console-breadcrumbs.test.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/test/console-breadcrumbs.test'>;
}
declare module 'bugsnag-js/browser/plugins/test/context.test.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/test/context.test'>;
}
declare module 'bugsnag-js/browser/plugins/test/device.test.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/test/device.test'>;
}
declare module 'bugsnag-js/browser/plugins/test/inline-script-content.test.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/test/inline-script-content.test'>;
}
declare module 'bugsnag-js/browser/plugins/test/interaction-breadcrumbs.test.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/test/interaction-breadcrumbs.test'>;
}
declare module 'bugsnag-js/browser/plugins/test/navigation-breadcrumbs.test.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/test/navigation-breadcrumbs.test'>;
}
declare module 'bugsnag-js/browser/plugins/test/request.test.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/test/request.test'>;
}
declare module 'bugsnag-js/browser/plugins/test/sessions.test.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/test/sessions.test'>;
}
declare module 'bugsnag-js/browser/plugins/test/unhandled-rejection.test.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/test/unhandled-rejection.test'>;
}
declare module 'bugsnag-js/browser/plugins/test/window-onerror.test.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/test/window-onerror.test'>;
}
declare module 'bugsnag-js/browser/plugins/unhandled-rejection.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/unhandled-rejection'>;
}
declare module 'bugsnag-js/browser/plugins/window-onerror.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/plugins/window-onerror'>;
}
declare module 'bugsnag-js/browser/test/client.test.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/test/client.test'>;
}
declare module 'bugsnag-js/browser/test/fixtures/handled-error-object.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/test/fixtures/handled-error-object'>;
}
declare module 'bugsnag-js/browser/test/fixtures/handled-error.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/test/fixtures/handled-error'>;
}
declare module 'bugsnag-js/browser/test/fixtures/unhandled-error-global.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/test/fixtures/unhandled-error-global'>;
}
declare module 'bugsnag-js/browser/test/fixtures/unhandled-error.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/test/fixtures/unhandled-error'>;
}
declare module 'bugsnag-js/browser/test/lib/echo-server.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/test/lib/echo-server'>;
}
declare module 'bugsnag-js/browser/test/lib/karma.conf.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/test/lib/karma.conf'>;
}
declare module 'bugsnag-js/browser/transports/lib/payload.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/transports/lib/payload'>;
}
declare module 'bugsnag-js/browser/transports/test/x-domain-request.test.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/transports/test/x-domain-request.test'>;
}
declare module 'bugsnag-js/browser/transports/test/xml-http-request.test.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/transports/test/xml-http-request.test'>;
}
declare module 'bugsnag-js/browser/transports/x-domain-request.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/transports/x-domain-request'>;
}
declare module 'bugsnag-js/browser/transports/xml-http-request.js' {
  declare module.exports: $Exports<'bugsnag-js/browser/transports/xml-http-request'>;
}
declare module 'bugsnag-js/dist/bugsnag.js' {
  declare module.exports: $Exports<'bugsnag-js/dist/bugsnag'>;
}
declare module 'bugsnag-js/dist/bugsnag.min.js' {
  declare module.exports: $Exports<'bugsnag-js/dist/bugsnag.min'>;
}
declare module 'bugsnag-js/e2e/browserify/app.js' {
  declare module.exports: $Exports<'bugsnag-js/e2e/browserify/app'>;
}
declare module 'bugsnag-js/e2e/browserify/assertions.test.js' {
  declare module.exports: $Exports<'bugsnag-js/e2e/browserify/assertions.test'>;
}
declare module 'bugsnag-js/e2e/browserify/build.js' {
  declare module.exports: $Exports<'bugsnag-js/e2e/browserify/build'>;
}
declare module 'bugsnag-js/e2e/lib/karma.conf.js' {
  declare module.exports: $Exports<'bugsnag-js/e2e/lib/karma.conf'>;
}
declare module 'bugsnag-js/e2e/lib/prepare.js' {
  declare module.exports: $Exports<'bugsnag-js/e2e/lib/prepare'>;
}
declare module 'bugsnag-js/e2e/script/assertions.test.js' {
  declare module.exports: $Exports<'bugsnag-js/e2e/script/assertions.test'>;
}
declare module 'bugsnag-js/e2e/script/build.js' {
  declare module.exports: $Exports<'bugsnag-js/e2e/script/build'>;
}
declare module 'bugsnag-js/e2e/typescript/assertions.test.js' {
  declare module.exports: $Exports<'bugsnag-js/e2e/typescript/assertions.test'>;
}
declare module 'bugsnag-js/e2e/typescript/build.js' {
  declare module.exports: $Exports<'bugsnag-js/e2e/typescript/build'>;
}
declare module 'bugsnag-js/e2e/webpack/app.js' {
  declare module.exports: $Exports<'bugsnag-js/e2e/webpack/app'>;
}
declare module 'bugsnag-js/e2e/webpack/assertions.test.js' {
  declare module.exports: $Exports<'bugsnag-js/e2e/webpack/assertions.test'>;
}
declare module 'bugsnag-js/e2e/webpack/build.js' {
  declare module.exports: $Exports<'bugsnag-js/e2e/webpack/build'>;
}
declare module 'bugsnag-js/e2e/webpack/webpack.config.js' {
  declare module.exports: $Exports<'bugsnag-js/e2e/webpack/webpack.config'>;
}
declare module 'bugsnag-js/examples/js/app.js' {
  declare module.exports: $Exports<'bugsnag-js/examples/js/app'>;
}
declare module 'bugsnag-js/examples/sourcemaps/app.js' {
  declare module.exports: $Exports<'bugsnag-js/examples/sourcemaps/app'>;
}
declare module 'bugsnag-js/node/index.js' {
  declare module.exports: $Exports<'bugsnag-js/node/index'>;
}
declare module 'bugsnag-js/types/test/fixtures/app.js' {
  declare module.exports: $Exports<'bugsnag-js/types/test/fixtures/app'>;
}
declare module 'bugsnag-js/types/test/types.test.js' {
  declare module.exports: $Exports<'bugsnag-js/types/test/types.test'>;
}
