// flow-typed signature: c8b4250443e7b0579ead6f67025c6a3d
// flow-typed version: <<STUB>>/bugsnag-react_vlatest/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bugsnag-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bugsnag-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bugsnag-react/dist/bugsnag-react' {
  declare module.exports: any;
}

declare module 'bugsnag-react/dist/bugsnag-react.min' {
  declare module.exports: any;
}

declare module 'bugsnag-react/src/index' {
  declare module.exports: any;
}

declare module 'bugsnag-react/src/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bugsnag-react/dist/bugsnag-react.js' {
  declare module.exports: $Exports<'bugsnag-react/dist/bugsnag-react'>;
}
declare module 'bugsnag-react/dist/bugsnag-react.min.js' {
  declare module.exports: $Exports<'bugsnag-react/dist/bugsnag-react.min'>;
}
declare module 'bugsnag-react/src/index.js' {
  declare module.exports: $Exports<'bugsnag-react/src/index'>;
}
declare module 'bugsnag-react/src/test/index.test.js' {
  declare module.exports: $Exports<'bugsnag-react/src/test/index.test'>;
}
