// flow-typed signature: 600007e4bc2ffb1893cba0a6f8d56489
// flow-typed version: <<STUB>>/css-variables-loader_v2.0.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-variables-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-variables-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-variables-loader/src/index' {
  declare module.exports: any;
}

declare module 'css-variables-loader/test/simple' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-variables-loader/src/index.js' {
  declare module.exports: $Exports<'css-variables-loader/src/index'>;
}
declare module 'css-variables-loader/test/simple.js' {
  declare module.exports: $Exports<'css-variables-loader/test/simple'>;
}
