// flow-typed signature: 61d0accc5f710452e30a119650bb38c9
// flow-typed version: <<STUB>>/escape-html_v^1.0.3/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'escape-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'escape-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'escape-html/index' {
  declare module.exports: $Exports<'escape-html'>;
}
declare module 'escape-html/index.js' {
  declare module.exports: $Exports<'escape-html'>;
}
