// flow-typed signature: 9eb8aad2eaeb3b220c0818da72e15f53
// flow-typed version: <<STUB>>/http-server_v0.11.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'http-server/lib/http-server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'http-server/lib/http-server.js' {
  declare module.exports: $Exports<'http-server/lib/http-server'>;
}
