// flow-typed signature: 0c73136e0aec0f39e4052dcfd21f4815
// flow-typed version: <<STUB>>/ignore-loader_v0.1.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ignore-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ignore-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ignore-loader/index' {
  declare module.exports: $Exports<'ignore-loader'>;
}
declare module 'ignore-loader/index.js' {
  declare module.exports: $Exports<'ignore-loader'>;
}
