// flow-typed signature: 078d27c8e5bcc62f313cf7989734d3e2
// flow-typed version: <<STUB>>/markdown-component-loader_v^0.8.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-component-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-component-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdown-component-loader/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'markdown-component-loader/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'markdown-component-loader/lib/formatters/import' {
  declare module.exports: any;
}

declare module 'markdown-component-loader/lib/formatters/module' {
  declare module.exports: any;
}

declare module 'markdown-component-loader/lib/formatters/static' {
  declare module.exports: any;
}

declare module 'markdown-component-loader/lib/hex-to-alpha' {
  declare module.exports: any;
}

declare module 'markdown-component-loader/lib/html-to-jsx' {
  declare module.exports: any;
}

declare module 'markdown-component-loader/lib/index' {
  declare module.exports: any;
}

declare module 'markdown-component-loader/lib/process-html' {
  declare module.exports: any;
}

declare module 'markdown-component-loader/lib/string-replacement-cache' {
  declare module.exports: any;
}

declare module 'markdown-component-loader/src/__fixtures__/components' {
  declare module.exports: any;
}

declare module 'markdown-component-loader/src/__mocks__/foo' {
  declare module.exports: any;
}

declare module 'markdown-component-loader/src/formatters/import' {
  declare module.exports: any;
}

declare module 'markdown-component-loader/src/formatters/module' {
  declare module.exports: any;
}

declare module 'markdown-component-loader/src/formatters/static' {
  declare module.exports: any;
}

declare module 'markdown-component-loader/src/html-to-jsx' {
  declare module.exports: any;
}

declare module 'markdown-component-loader/src/index' {
  declare module.exports: any;
}

declare module 'markdown-component-loader/src/string-replacement-cache' {
  declare module.exports: any;
}

declare module 'markdown-component-loader/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdown-component-loader/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'markdown-component-loader/coverage/lcov-report/prettify'>;
}
declare module 'markdown-component-loader/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'markdown-component-loader/coverage/lcov-report/sorter'>;
}
declare module 'markdown-component-loader/lib/formatters/import.js' {
  declare module.exports: $Exports<'markdown-component-loader/lib/formatters/import'>;
}
declare module 'markdown-component-loader/lib/formatters/module.js' {
  declare module.exports: $Exports<'markdown-component-loader/lib/formatters/module'>;
}
declare module 'markdown-component-loader/lib/formatters/static.js' {
  declare module.exports: $Exports<'markdown-component-loader/lib/formatters/static'>;
}
declare module 'markdown-component-loader/lib/hex-to-alpha.js' {
  declare module.exports: $Exports<'markdown-component-loader/lib/hex-to-alpha'>;
}
declare module 'markdown-component-loader/lib/html-to-jsx.js' {
  declare module.exports: $Exports<'markdown-component-loader/lib/html-to-jsx'>;
}
declare module 'markdown-component-loader/lib/index.js' {
  declare module.exports: $Exports<'markdown-component-loader/lib/index'>;
}
declare module 'markdown-component-loader/lib/process-html.js' {
  declare module.exports: $Exports<'markdown-component-loader/lib/process-html'>;
}
declare module 'markdown-component-loader/lib/string-replacement-cache.js' {
  declare module.exports: $Exports<'markdown-component-loader/lib/string-replacement-cache'>;
}
declare module 'markdown-component-loader/src/__fixtures__/components.js' {
  declare module.exports: $Exports<'markdown-component-loader/src/__fixtures__/components'>;
}
declare module 'markdown-component-loader/src/__mocks__/foo.js' {
  declare module.exports: $Exports<'markdown-component-loader/src/__mocks__/foo'>;
}
declare module 'markdown-component-loader/src/formatters/import.js' {
  declare module.exports: $Exports<'markdown-component-loader/src/formatters/import'>;
}
declare module 'markdown-component-loader/src/formatters/module.js' {
  declare module.exports: $Exports<'markdown-component-loader/src/formatters/module'>;
}
declare module 'markdown-component-loader/src/formatters/static.js' {
  declare module.exports: $Exports<'markdown-component-loader/src/formatters/static'>;
}
declare module 'markdown-component-loader/src/html-to-jsx.js' {
  declare module.exports: $Exports<'markdown-component-loader/src/html-to-jsx'>;
}
declare module 'markdown-component-loader/src/index.js' {
  declare module.exports: $Exports<'markdown-component-loader/src/index'>;
}
declare module 'markdown-component-loader/src/string-replacement-cache.js' {
  declare module.exports: $Exports<'markdown-component-loader/src/string-replacement-cache'>;
}
declare module 'markdown-component-loader/webpack.config.js' {
  declare module.exports: $Exports<'markdown-component-loader/webpack.config'>;
}
