// flow-typed signature: b93d043c9ee9737782f0c91277f02353
// flow-typed version: <<STUB>>/metrick_v^0.2.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'metrick'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'metrick' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'metrick/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'metrick/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'metrick/data' {
  declare module.exports: any;
}

declare module 'metrick/duration' {
  declare module.exports: any;
}

declare module 'metrick/length' {
  declare module.exports: any;
}

declare module 'metrick/src/data' {
  declare module.exports: any;
}

declare module 'metrick/src/duration' {
  declare module.exports: any;
}

declare module 'metrick/src/index' {
  declare module.exports: any;
}

declare module 'metrick/src/length' {
  declare module.exports: any;
}

declare module 'metrick/src/temperature' {
  declare module.exports: any;
}

declare module 'metrick/src/unit' {
  declare module.exports: any;
}

declare module 'metrick/temperature' {
  declare module.exports: any;
}

declare module 'metrick/unit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'metrick/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'metrick/coverage/lcov-report/prettify'>;
}
declare module 'metrick/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'metrick/coverage/lcov-report/sorter'>;
}
declare module 'metrick/data.js' {
  declare module.exports: $Exports<'metrick/data'>;
}
declare module 'metrick/duration.js' {
  declare module.exports: $Exports<'metrick/duration'>;
}
declare module 'metrick/index' {
  declare module.exports: $Exports<'metrick'>;
}
declare module 'metrick/index.js' {
  declare module.exports: $Exports<'metrick'>;
}
declare module 'metrick/length.js' {
  declare module.exports: $Exports<'metrick/length'>;
}
declare module 'metrick/src/data.js' {
  declare module.exports: $Exports<'metrick/src/data'>;
}
declare module 'metrick/src/duration.js' {
  declare module.exports: $Exports<'metrick/src/duration'>;
}
declare module 'metrick/src/index.js' {
  declare module.exports: $Exports<'metrick/src/index'>;
}
declare module 'metrick/src/length.js' {
  declare module.exports: $Exports<'metrick/src/length'>;
}
declare module 'metrick/src/temperature.js' {
  declare module.exports: $Exports<'metrick/src/temperature'>;
}
declare module 'metrick/src/unit.js' {
  declare module.exports: $Exports<'metrick/src/unit'>;
}
declare module 'metrick/temperature.js' {
  declare module.exports: $Exports<'metrick/temperature'>;
}
declare module 'metrick/unit.js' {
  declare module.exports: $Exports<'metrick/unit'>;
}
