// flow-typed signature: 67c594fbf728c4d58dd6b5840fc7f3b6
// flow-typed version: <<STUB>>/mojibaka_v1.0.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mojibaka'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mojibaka' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mojibaka/canvas' {
  declare module.exports: any;
}

declare module 'mojibaka/detect/fitzpatrick' {
  declare module.exports: any;
}

declare module 'mojibaka/detect/genders' {
  declare module.exports: any;
}

declare module 'mojibaka/detect/scale' {
  declare module.exports: any;
}

declare module 'mojibaka/detect/version' {
  declare module.exports: any;
}

declare module 'mojibaka/dom' {
  declare module.exports: any;
}

declare module 'mojibaka/package 2/index' {
  declare module.exports: any;
}

declare module 'mojibaka/package 2/src/canvas' {
  declare module.exports: any;
}

declare module 'mojibaka/package 2/src/detect/fitzpatrick' {
  declare module.exports: any;
}

declare module 'mojibaka/package 2/src/detect/genders' {
  declare module.exports: any;
}

declare module 'mojibaka/package 2/src/detect/scale' {
  declare module.exports: any;
}

declare module 'mojibaka/package 2/src/detect/version' {
  declare module.exports: any;
}

declare module 'mojibaka/package 2/src/dom' {
  declare module.exports: any;
}

declare module 'mojibaka/package 2/src/index' {
  declare module.exports: any;
}

declare module 'mojibaka/package/canvas' {
  declare module.exports: any;
}

declare module 'mojibaka/package/detect/fitzpatrick' {
  declare module.exports: any;
}

declare module 'mojibaka/package/detect/genders' {
  declare module.exports: any;
}

declare module 'mojibaka/package/detect/scale' {
  declare module.exports: any;
}

declare module 'mojibaka/package/detect/version' {
  declare module.exports: any;
}

declare module 'mojibaka/package/dom' {
  declare module.exports: any;
}

declare module 'mojibaka/package/index' {
  declare module.exports: any;
}

declare module 'mojibaka/package/src/canvas' {
  declare module.exports: any;
}

declare module 'mojibaka/package/src/detect/fitzpatrick' {
  declare module.exports: any;
}

declare module 'mojibaka/package/src/detect/genders' {
  declare module.exports: any;
}

declare module 'mojibaka/package/src/detect/scale' {
  declare module.exports: any;
}

declare module 'mojibaka/package/src/detect/version' {
  declare module.exports: any;
}

declare module 'mojibaka/package/src/dom' {
  declare module.exports: any;
}

declare module 'mojibaka/package/src/index' {
  declare module.exports: any;
}

declare module 'mojibaka/package/webpack.config' {
  declare module.exports: any;
}

declare module 'mojibaka/src/canvas' {
  declare module.exports: any;
}

declare module 'mojibaka/src/detect/fitzpatrick' {
  declare module.exports: any;
}

declare module 'mojibaka/src/detect/genders' {
  declare module.exports: any;
}

declare module 'mojibaka/src/detect/scale' {
  declare module.exports: any;
}

declare module 'mojibaka/src/detect/version' {
  declare module.exports: any;
}

declare module 'mojibaka/src/dom' {
  declare module.exports: any;
}

declare module 'mojibaka/src/index' {
  declare module.exports: any;
}

declare module 'mojibaka/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mojibaka/canvas.js' {
  declare module.exports: $Exports<'mojibaka/canvas'>;
}
declare module 'mojibaka/detect/fitzpatrick.js' {
  declare module.exports: $Exports<'mojibaka/detect/fitzpatrick'>;
}
declare module 'mojibaka/detect/genders.js' {
  declare module.exports: $Exports<'mojibaka/detect/genders'>;
}
declare module 'mojibaka/detect/scale.js' {
  declare module.exports: $Exports<'mojibaka/detect/scale'>;
}
declare module 'mojibaka/detect/version.js' {
  declare module.exports: $Exports<'mojibaka/detect/version'>;
}
declare module 'mojibaka/dom.js' {
  declare module.exports: $Exports<'mojibaka/dom'>;
}
declare module 'mojibaka/index' {
  declare module.exports: $Exports<'mojibaka'>;
}
declare module 'mojibaka/index.js' {
  declare module.exports: $Exports<'mojibaka'>;
}
declare module 'mojibaka/package 2/index.js' {
  declare module.exports: $Exports<'mojibaka/package 2/index'>;
}
declare module 'mojibaka/package 2/src/canvas.js' {
  declare module.exports: $Exports<'mojibaka/package 2/src/canvas'>;
}
declare module 'mojibaka/package 2/src/detect/fitzpatrick.js' {
  declare module.exports: $Exports<'mojibaka/package 2/src/detect/fitzpatrick'>;
}
declare module 'mojibaka/package 2/src/detect/genders.js' {
  declare module.exports: $Exports<'mojibaka/package 2/src/detect/genders'>;
}
declare module 'mojibaka/package 2/src/detect/scale.js' {
  declare module.exports: $Exports<'mojibaka/package 2/src/detect/scale'>;
}
declare module 'mojibaka/package 2/src/detect/version.js' {
  declare module.exports: $Exports<'mojibaka/package 2/src/detect/version'>;
}
declare module 'mojibaka/package 2/src/dom.js' {
  declare module.exports: $Exports<'mojibaka/package 2/src/dom'>;
}
declare module 'mojibaka/package 2/src/index.js' {
  declare module.exports: $Exports<'mojibaka/package 2/src/index'>;
}
declare module 'mojibaka/package/canvas.js' {
  declare module.exports: $Exports<'mojibaka/package/canvas'>;
}
declare module 'mojibaka/package/detect/fitzpatrick.js' {
  declare module.exports: $Exports<'mojibaka/package/detect/fitzpatrick'>;
}
declare module 'mojibaka/package/detect/genders.js' {
  declare module.exports: $Exports<'mojibaka/package/detect/genders'>;
}
declare module 'mojibaka/package/detect/scale.js' {
  declare module.exports: $Exports<'mojibaka/package/detect/scale'>;
}
declare module 'mojibaka/package/detect/version.js' {
  declare module.exports: $Exports<'mojibaka/package/detect/version'>;
}
declare module 'mojibaka/package/dom.js' {
  declare module.exports: $Exports<'mojibaka/package/dom'>;
}
declare module 'mojibaka/package/index.js' {
  declare module.exports: $Exports<'mojibaka/package/index'>;
}
declare module 'mojibaka/package/src/canvas.js' {
  declare module.exports: $Exports<'mojibaka/package/src/canvas'>;
}
declare module 'mojibaka/package/src/detect/fitzpatrick.js' {
  declare module.exports: $Exports<'mojibaka/package/src/detect/fitzpatrick'>;
}
declare module 'mojibaka/package/src/detect/genders.js' {
  declare module.exports: $Exports<'mojibaka/package/src/detect/genders'>;
}
declare module 'mojibaka/package/src/detect/scale.js' {
  declare module.exports: $Exports<'mojibaka/package/src/detect/scale'>;
}
declare module 'mojibaka/package/src/detect/version.js' {
  declare module.exports: $Exports<'mojibaka/package/src/detect/version'>;
}
declare module 'mojibaka/package/src/dom.js' {
  declare module.exports: $Exports<'mojibaka/package/src/dom'>;
}
declare module 'mojibaka/package/src/index.js' {
  declare module.exports: $Exports<'mojibaka/package/src/index'>;
}
declare module 'mojibaka/package/webpack.config.js' {
  declare module.exports: $Exports<'mojibaka/package/webpack.config'>;
}
declare module 'mojibaka/src/canvas.js' {
  declare module.exports: $Exports<'mojibaka/src/canvas'>;
}
declare module 'mojibaka/src/detect/fitzpatrick.js' {
  declare module.exports: $Exports<'mojibaka/src/detect/fitzpatrick'>;
}
declare module 'mojibaka/src/detect/genders.js' {
  declare module.exports: $Exports<'mojibaka/src/detect/genders'>;
}
declare module 'mojibaka/src/detect/scale.js' {
  declare module.exports: $Exports<'mojibaka/src/detect/scale'>;
}
declare module 'mojibaka/src/detect/version.js' {
  declare module.exports: $Exports<'mojibaka/src/detect/version'>;
}
declare module 'mojibaka/src/dom.js' {
  declare module.exports: $Exports<'mojibaka/src/dom'>;
}
declare module 'mojibaka/src/index.js' {
  declare module.exports: $Exports<'mojibaka/src/index'>;
}
declare module 'mojibaka/webpack.config.js' {
  declare module.exports: $Exports<'mojibaka/webpack.config'>;
}
