// flow-typed signature: 8e4f651f4311f445570970f98e013b6a
// flow-typed version: <<STUB>>/moment-duration-format_vhttps://github.com/ticky/moment-duration-format.git#951b8be1d1b0424824363aa912cbf066546bf384/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment-duration-format'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moment-duration-format' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'moment-duration-format/lib/moment-duration-format' {
  declare module.exports: any;
}

declare module 'moment-duration-format/test/moment-duration-format-tests' {
  declare module.exports: any;
}

declare module 'moment-duration-format/test/vendor/jquery' {
  declare module.exports: any;
}

declare module 'moment-duration-format/test/vendor/moment' {
  declare module.exports: any;
}

declare module 'moment-duration-format/test/vendor/qunit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'moment-duration-format/lib/moment-duration-format.js' {
  declare module.exports: $Exports<'moment-duration-format/lib/moment-duration-format'>;
}
declare module 'moment-duration-format/test/moment-duration-format-tests.js' {
  declare module.exports: $Exports<'moment-duration-format/test/moment-duration-format-tests'>;
}
declare module 'moment-duration-format/test/vendor/jquery.js' {
  declare module.exports: $Exports<'moment-duration-format/test/vendor/jquery'>;
}
declare module 'moment-duration-format/test/vendor/moment.js' {
  declare module.exports: $Exports<'moment-duration-format/test/vendor/moment'>;
}
declare module 'moment-duration-format/test/vendor/qunit.js' {
  declare module.exports: $Exports<'moment-duration-format/test/vendor/qunit'>;
}
