// flow-typed signature: bff5c3b43aa2a1f23f04b14c1245aa67
// flow-typed version: <<STUB>>/n-shuffle_v1.0.4/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'n-shuffle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'n-shuffle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'n-shuffle/index' {
  declare module.exports: $Exports<'n-shuffle'>;
}
declare module 'n-shuffle/index.js' {
  declare module.exports: $Exports<'n-shuffle'>;
}
