// flow-typed signature: fd45654e04d69129c9bb814116a00537
// flow-typed version: <<STUB>>/postcss-easings_v1.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-easings'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-easings' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-easings/index' {
  declare module.exports: $Exports<'postcss-easings'>;
}
declare module 'postcss-easings/index.js' {
  declare module.exports: $Exports<'postcss-easings'>;
}
