// flow-typed signature: 7b5d55bd08e67424dd8b4f2b3d93c6f9
// flow-typed version: <<STUB>>/pusher-js_v^4.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pusher-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pusher-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pusher-js/demos/light/app' {
  declare module.exports: any;
}

declare module 'pusher-js/dist/node/pusher' {
  declare module.exports: any;
}

declare module 'pusher-js/dist/react-native/pusher' {
  declare module.exports: any;
}

declare module 'pusher-js/dist/web/json2' {
  declare module.exports: any;
}

declare module 'pusher-js/dist/web/json2.min' {
  declare module.exports: any;
}

declare module 'pusher-js/dist/web/pusher' {
  declare module.exports: any;
}

declare module 'pusher-js/dist/web/pusher.min' {
  declare module.exports: any;
}

declare module 'pusher-js/dist/web/sockjs' {
  declare module.exports: any;
}

declare module 'pusher-js/dist/web/sockjs.min' {
  declare module.exports: any;
}

declare module 'pusher-js/dist/worker/pusher.worker' {
  declare module.exports: any;
}

declare module 'pusher-js/dist/worker/pusher.worker.min' {
  declare module.exports: any;
}

declare module 'pusher-js/node' {
  declare module.exports: any;
}

declare module 'pusher-js/react-native' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/config/jasmine-node/config' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/config/jasmine-node/webpack.integration' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/config/jasmine-node/webpack.unit' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/config/karma/config.ci' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/config/karma/config.common' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/config/karma/config.integration' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/config/karma/config.unit' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/config/karma/config.worker' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/config/karma/integration' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/config/karma/unit' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/helpers/mocks' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/helpers/node/integration' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/helpers/web/integration' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/integration/core/cluster_config_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/integration/core/falling_back_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/integration/core/pusher_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/integration/core/timeout_configuration_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/integration/core/transport_lists_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/integration/index.node' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/integration/index.web' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/integration/index.worker' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/integration/web/dom/jsonp_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/integration/web/dom/script_request_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/polyfills/index' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/channels/channel_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/channels/channels_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/channels/presence_channel_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/channels/private_channel_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/connection/connection_manager_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/connection/connection_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/connection/handshake_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/connection/protocol_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/defaults_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/events_dispatcher_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/http/http_polling_socket_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/http/http_request_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/http/http_socket_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/http/http_streaming_socket_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/http/http_xhr_request_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/logger_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/pusher_authorizer_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/pusher_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/strategies/best_connected_ever_strategy_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/strategies/cached_strategy_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/strategies/delayed_strategy_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/strategies/first_connected_strategy_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/strategies/if_strategy_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/strategies/sequential_strategy_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/strategies/strategy_builder_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/strategies/transport_strategy_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/timeline/timeline_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/transports/assistant_to_the_transport_manager_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/transports/hosts_and_ports_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/transports/transport_connection_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/transports/transport_manager_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/utils/periodic_timer_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/core/utils/timers_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/index.node' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/index.web' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/index.worker' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/isomorphic/transports/hosts_and_ports_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/isomorphic/transports/transports_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/node/timeline_sender_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/web/dom/dependency_loader_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/web/dom/jsonp_request_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/web/dom/script_receiver_factory_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/web/http/http_xdomain_request_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/web/pusher_authorizer_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/web/timeline/timeline_sender_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/web/transports/hosts_and_ports_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/web/transports/transports_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/worker/pusher_authorizer_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/spec/javascripts/unit/worker/timeline_sender_spec' {
  declare module.exports: any;
}

declare module 'pusher-js/src/core/pusher-licence' {
  declare module.exports: any;
}

declare module 'pusher-js/src/runtimes/web/dom/json2' {
  declare module.exports: any;
}

declare module 'pusher-js/webpack/config.min' {
  declare module.exports: any;
}

declare module 'pusher-js/webpack/config.node' {
  declare module.exports: any;
}

declare module 'pusher-js/webpack/config.react-native' {
  declare module.exports: any;
}

declare module 'pusher-js/webpack/config.shared' {
  declare module.exports: any;
}

declare module 'pusher-js/webpack/config.web' {
  declare module.exports: any;
}

declare module 'pusher-js/webpack/config.worker' {
  declare module.exports: any;
}

declare module 'pusher-js/webpack/dev.server' {
  declare module.exports: any;
}

declare module 'pusher-js/webpack/hosting_config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pusher-js/demos/light/app.js' {
  declare module.exports: $Exports<'pusher-js/demos/light/app'>;
}
declare module 'pusher-js/dist/node/pusher.js' {
  declare module.exports: $Exports<'pusher-js/dist/node/pusher'>;
}
declare module 'pusher-js/dist/react-native/pusher.js' {
  declare module.exports: $Exports<'pusher-js/dist/react-native/pusher'>;
}
declare module 'pusher-js/dist/web/json2.js' {
  declare module.exports: $Exports<'pusher-js/dist/web/json2'>;
}
declare module 'pusher-js/dist/web/json2.min.js' {
  declare module.exports: $Exports<'pusher-js/dist/web/json2.min'>;
}
declare module 'pusher-js/dist/web/pusher.js' {
  declare module.exports: $Exports<'pusher-js/dist/web/pusher'>;
}
declare module 'pusher-js/dist/web/pusher.min.js' {
  declare module.exports: $Exports<'pusher-js/dist/web/pusher.min'>;
}
declare module 'pusher-js/dist/web/sockjs.js' {
  declare module.exports: $Exports<'pusher-js/dist/web/sockjs'>;
}
declare module 'pusher-js/dist/web/sockjs.min.js' {
  declare module.exports: $Exports<'pusher-js/dist/web/sockjs.min'>;
}
declare module 'pusher-js/dist/worker/pusher.worker.js' {
  declare module.exports: $Exports<'pusher-js/dist/worker/pusher.worker'>;
}
declare module 'pusher-js/dist/worker/pusher.worker.min.js' {
  declare module.exports: $Exports<'pusher-js/dist/worker/pusher.worker.min'>;
}
declare module 'pusher-js/node.js' {
  declare module.exports: $Exports<'pusher-js/node'>;
}
declare module 'pusher-js/react-native.js' {
  declare module.exports: $Exports<'pusher-js/react-native'>;
}
declare module 'pusher-js/spec/config/jasmine-node/config.js' {
  declare module.exports: $Exports<'pusher-js/spec/config/jasmine-node/config'>;
}
declare module 'pusher-js/spec/config/jasmine-node/webpack.integration.js' {
  declare module.exports: $Exports<'pusher-js/spec/config/jasmine-node/webpack.integration'>;
}
declare module 'pusher-js/spec/config/jasmine-node/webpack.unit.js' {
  declare module.exports: $Exports<'pusher-js/spec/config/jasmine-node/webpack.unit'>;
}
declare module 'pusher-js/spec/config/karma/config.ci.js' {
  declare module.exports: $Exports<'pusher-js/spec/config/karma/config.ci'>;
}
declare module 'pusher-js/spec/config/karma/config.common.js' {
  declare module.exports: $Exports<'pusher-js/spec/config/karma/config.common'>;
}
declare module 'pusher-js/spec/config/karma/config.integration.js' {
  declare module.exports: $Exports<'pusher-js/spec/config/karma/config.integration'>;
}
declare module 'pusher-js/spec/config/karma/config.unit.js' {
  declare module.exports: $Exports<'pusher-js/spec/config/karma/config.unit'>;
}
declare module 'pusher-js/spec/config/karma/config.worker.js' {
  declare module.exports: $Exports<'pusher-js/spec/config/karma/config.worker'>;
}
declare module 'pusher-js/spec/config/karma/integration.js' {
  declare module.exports: $Exports<'pusher-js/spec/config/karma/integration'>;
}
declare module 'pusher-js/spec/config/karma/unit.js' {
  declare module.exports: $Exports<'pusher-js/spec/config/karma/unit'>;
}
declare module 'pusher-js/spec/javascripts/helpers/mocks.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/helpers/mocks'>;
}
declare module 'pusher-js/spec/javascripts/helpers/node/integration.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/helpers/node/integration'>;
}
declare module 'pusher-js/spec/javascripts/helpers/web/integration.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/helpers/web/integration'>;
}
declare module 'pusher-js/spec/javascripts/integration/core/cluster_config_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/integration/core/cluster_config_spec'>;
}
declare module 'pusher-js/spec/javascripts/integration/core/falling_back_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/integration/core/falling_back_spec'>;
}
declare module 'pusher-js/spec/javascripts/integration/core/pusher_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/integration/core/pusher_spec'>;
}
declare module 'pusher-js/spec/javascripts/integration/core/timeout_configuration_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/integration/core/timeout_configuration_spec'>;
}
declare module 'pusher-js/spec/javascripts/integration/core/transport_lists_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/integration/core/transport_lists_spec'>;
}
declare module 'pusher-js/spec/javascripts/integration/index.node.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/integration/index.node'>;
}
declare module 'pusher-js/spec/javascripts/integration/index.web.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/integration/index.web'>;
}
declare module 'pusher-js/spec/javascripts/integration/index.worker.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/integration/index.worker'>;
}
declare module 'pusher-js/spec/javascripts/integration/web/dom/jsonp_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/integration/web/dom/jsonp_spec'>;
}
declare module 'pusher-js/spec/javascripts/integration/web/dom/script_request_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/integration/web/dom/script_request_spec'>;
}
declare module 'pusher-js/spec/javascripts/polyfills/index.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/polyfills/index'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/channels/channel_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/channels/channel_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/channels/channels_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/channels/channels_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/channels/presence_channel_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/channels/presence_channel_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/channels/private_channel_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/channels/private_channel_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/connection/connection_manager_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/connection/connection_manager_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/connection/connection_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/connection/connection_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/connection/handshake_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/connection/handshake_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/connection/protocol_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/connection/protocol_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/defaults_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/defaults_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/events_dispatcher_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/events_dispatcher_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/http/http_polling_socket_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/http/http_polling_socket_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/http/http_request_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/http/http_request_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/http/http_socket_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/http/http_socket_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/http/http_streaming_socket_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/http/http_streaming_socket_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/http/http_xhr_request_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/http/http_xhr_request_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/logger_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/logger_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/pusher_authorizer_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/pusher_authorizer_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/pusher_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/pusher_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/strategies/best_connected_ever_strategy_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/strategies/best_connected_ever_strategy_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/strategies/cached_strategy_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/strategies/cached_strategy_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/strategies/delayed_strategy_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/strategies/delayed_strategy_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/strategies/first_connected_strategy_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/strategies/first_connected_strategy_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/strategies/if_strategy_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/strategies/if_strategy_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/strategies/sequential_strategy_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/strategies/sequential_strategy_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/strategies/strategy_builder_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/strategies/strategy_builder_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/strategies/transport_strategy_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/strategies/transport_strategy_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/timeline/timeline_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/timeline/timeline_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/transports/assistant_to_the_transport_manager_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/transports/assistant_to_the_transport_manager_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/transports/hosts_and_ports_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/transports/hosts_and_ports_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/transports/transport_connection_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/transports/transport_connection_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/transports/transport_manager_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/transports/transport_manager_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/utils/periodic_timer_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/utils/periodic_timer_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/core/utils/timers_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/core/utils/timers_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/index.node.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/index.node'>;
}
declare module 'pusher-js/spec/javascripts/unit/index.web.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/index.web'>;
}
declare module 'pusher-js/spec/javascripts/unit/index.worker.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/index.worker'>;
}
declare module 'pusher-js/spec/javascripts/unit/isomorphic/transports/hosts_and_ports_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/isomorphic/transports/hosts_and_ports_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/isomorphic/transports/transports_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/isomorphic/transports/transports_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/node/timeline_sender_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/node/timeline_sender_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/web/dom/dependency_loader_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/web/dom/dependency_loader_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/web/dom/jsonp_request_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/web/dom/jsonp_request_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/web/dom/script_receiver_factory_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/web/dom/script_receiver_factory_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/web/http/http_xdomain_request_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/web/http/http_xdomain_request_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/web/pusher_authorizer_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/web/pusher_authorizer_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/web/timeline/timeline_sender_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/web/timeline/timeline_sender_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/web/transports/hosts_and_ports_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/web/transports/hosts_and_ports_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/web/transports/transports_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/web/transports/transports_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/worker/pusher_authorizer_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/worker/pusher_authorizer_spec'>;
}
declare module 'pusher-js/spec/javascripts/unit/worker/timeline_sender_spec.js' {
  declare module.exports: $Exports<'pusher-js/spec/javascripts/unit/worker/timeline_sender_spec'>;
}
declare module 'pusher-js/src/core/pusher-licence.js' {
  declare module.exports: $Exports<'pusher-js/src/core/pusher-licence'>;
}
declare module 'pusher-js/src/runtimes/web/dom/json2.js' {
  declare module.exports: $Exports<'pusher-js/src/runtimes/web/dom/json2'>;
}
declare module 'pusher-js/webpack/config.min.js' {
  declare module.exports: $Exports<'pusher-js/webpack/config.min'>;
}
declare module 'pusher-js/webpack/config.node.js' {
  declare module.exports: $Exports<'pusher-js/webpack/config.node'>;
}
declare module 'pusher-js/webpack/config.react-native.js' {
  declare module.exports: $Exports<'pusher-js/webpack/config.react-native'>;
}
declare module 'pusher-js/webpack/config.shared.js' {
  declare module.exports: $Exports<'pusher-js/webpack/config.shared'>;
}
declare module 'pusher-js/webpack/config.web.js' {
  declare module.exports: $Exports<'pusher-js/webpack/config.web'>;
}
declare module 'pusher-js/webpack/config.worker.js' {
  declare module.exports: $Exports<'pusher-js/webpack/config.worker'>;
}
declare module 'pusher-js/webpack/dev.server.js' {
  declare module.exports: $Exports<'pusher-js/webpack/dev.server'>;
}
declare module 'pusher-js/webpack/hosting_config.js' {
  declare module.exports: $Exports<'pusher-js/webpack/hosting_config'>;
}
