// flow-typed signature: 6da46d546b4a1a2342772de95ebe34f0
// flow-typed version: <<STUB>>/react-router-relay_vhttps://github.com/sj26/react-router-relay/releases/download/v0.13.7%2Bclassic/react-router-relay-0.13.7.classic.tgz/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-relay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-relay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-relay/es/index' {
  declare module.exports: any;
}

declare module 'react-router-relay/es/QueryAggregator' {
  declare module.exports: any;
}

declare module 'react-router-relay/es/RelayRouterContext' {
  declare module.exports: any;
}

declare module 'react-router-relay/es/RouteContainer' {
  declare module.exports: any;
}

declare module 'react-router-relay/es/utils/getRouteQueries' {
  declare module.exports: any;
}

declare module 'react-router-relay/es/utils/mergeRouteParams' {
  declare module.exports: any;
}

declare module 'react-router-relay/lib/index' {
  declare module.exports: any;
}

declare module 'react-router-relay/lib/QueryAggregator' {
  declare module.exports: any;
}

declare module 'react-router-relay/lib/RelayRouterContext' {
  declare module.exports: any;
}

declare module 'react-router-relay/lib/RouteContainer' {
  declare module.exports: any;
}

declare module 'react-router-relay/lib/utils/getRouteQueries' {
  declare module.exports: any;
}

declare module 'react-router-relay/lib/utils/mergeRouteParams' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-relay/es/index.js' {
  declare module.exports: $Exports<'react-router-relay/es/index'>;
}
declare module 'react-router-relay/es/QueryAggregator.js' {
  declare module.exports: $Exports<'react-router-relay/es/QueryAggregator'>;
}
declare module 'react-router-relay/es/RelayRouterContext.js' {
  declare module.exports: $Exports<'react-router-relay/es/RelayRouterContext'>;
}
declare module 'react-router-relay/es/RouteContainer.js' {
  declare module.exports: $Exports<'react-router-relay/es/RouteContainer'>;
}
declare module 'react-router-relay/es/utils/getRouteQueries.js' {
  declare module.exports: $Exports<'react-router-relay/es/utils/getRouteQueries'>;
}
declare module 'react-router-relay/es/utils/mergeRouteParams.js' {
  declare module.exports: $Exports<'react-router-relay/es/utils/mergeRouteParams'>;
}
declare module 'react-router-relay/lib/index.js' {
  declare module.exports: $Exports<'react-router-relay/lib/index'>;
}
declare module 'react-router-relay/lib/QueryAggregator.js' {
  declare module.exports: $Exports<'react-router-relay/lib/QueryAggregator'>;
}
declare module 'react-router-relay/lib/RelayRouterContext.js' {
  declare module.exports: $Exports<'react-router-relay/lib/RelayRouterContext'>;
}
declare module 'react-router-relay/lib/RouteContainer.js' {
  declare module.exports: $Exports<'react-router-relay/lib/RouteContainer'>;
}
declare module 'react-router-relay/lib/utils/getRouteQueries.js' {
  declare module.exports: $Exports<'react-router-relay/lib/utils/getRouteQueries'>;
}
declare module 'react-router-relay/lib/utils/mergeRouteParams.js' {
  declare module.exports: $Exports<'react-router-relay/lib/utils/mergeRouteParams'>;
}
