// flow-typed signature: 7b2157a4fcc8b77b18369354247b63f3
// flow-typed version: <<STUB>>/react-addons-update_v^15.3.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-addons-update'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-addons-update' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-addons-update/react-addons-update' {
  declare module.exports: any;
}

declare module 'react-addons-update/react-addons-update.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-addons-update/index' {
  declare module.exports: $Exports<'react-addons-update'>;
}
declare module 'react-addons-update/index.js' {
  declare module.exports: $Exports<'react-addons-update'>;
}
declare module 'react-addons-update/react-addons-update.js' {
  declare module.exports: $Exports<'react-addons-update/react-addons-update'>;
}
declare module 'react-addons-update/react-addons-update.min.js' {
  declare module.exports: $Exports<'react-addons-update/react-addons-update.min'>;
}
