// flow-typed signature: 53de06da095675c0b1d5be21cb8572e7
// flow-typed version: <<STUB>>/react-type-snob_v^0.0.3/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-type-snob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-type-snob' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-type-snob/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'react-type-snob/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'react-type-snob/lib/console-reporter' {
  declare module.exports: any;
}

declare module 'react-type-snob/lib/get-display-name' {
  declare module.exports: any;
}

declare module 'react-type-snob/lib/index' {
  declare module.exports: any;
}

declare module 'react-type-snob/lib/verify-react' {
  declare module.exports: any;
}

declare module 'react-type-snob/src/console-reporter' {
  declare module.exports: any;
}

declare module 'react-type-snob/src/get-display-name' {
  declare module.exports: any;
}

declare module 'react-type-snob/src/get-display-name.spec' {
  declare module.exports: any;
}

declare module 'react-type-snob/src/index' {
  declare module.exports: any;
}

declare module 'react-type-snob/src/index.spec' {
  declare module.exports: any;
}

declare module 'react-type-snob/src/verify-react' {
  declare module.exports: any;
}

declare module 'react-type-snob/src/verify-react.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-type-snob/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'react-type-snob/coverage/lcov-report/prettify'>;
}
declare module 'react-type-snob/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'react-type-snob/coverage/lcov-report/sorter'>;
}
declare module 'react-type-snob/lib/console-reporter.js' {
  declare module.exports: $Exports<'react-type-snob/lib/console-reporter'>;
}
declare module 'react-type-snob/lib/get-display-name.js' {
  declare module.exports: $Exports<'react-type-snob/lib/get-display-name'>;
}
declare module 'react-type-snob/lib/index.js' {
  declare module.exports: $Exports<'react-type-snob/lib/index'>;
}
declare module 'react-type-snob/lib/verify-react.js' {
  declare module.exports: $Exports<'react-type-snob/lib/verify-react'>;
}
declare module 'react-type-snob/src/console-reporter.js' {
  declare module.exports: $Exports<'react-type-snob/src/console-reporter'>;
}
declare module 'react-type-snob/src/get-display-name.js' {
  declare module.exports: $Exports<'react-type-snob/src/get-display-name'>;
}
declare module 'react-type-snob/src/get-display-name.spec.js' {
  declare module.exports: $Exports<'react-type-snob/src/get-display-name.spec'>;
}
declare module 'react-type-snob/src/index.js' {
  declare module.exports: $Exports<'react-type-snob/src/index'>;
}
declare module 'react-type-snob/src/index.spec.js' {
  declare module.exports: $Exports<'react-type-snob/src/index.spec'>;
}
declare module 'react-type-snob/src/verify-react.js' {
  declare module.exports: $Exports<'react-type-snob/src/verify-react'>;
}
declare module 'react-type-snob/src/verify-react.spec.js' {
  declare module.exports: $Exports<'react-type-snob/src/verify-react.spec'>;
}
