// flow-typed signature: 94d7e4678909ec7f6149610746969632
// flow-typed version: <<STUB>>/react-document-title_v^2.0.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-document-title'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-document-title' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-document-title/test/browser' {
  declare module.exports: any;
}

declare module 'react-document-title/test/common' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-document-title/index' {
  declare module.exports: $Exports<'react-document-title'>;
}
declare module 'react-document-title/index.js' {
  declare module.exports: $Exports<'react-document-title'>;
}
declare module 'react-document-title/test/browser.js' {
  declare module.exports: $Exports<'react-document-title/test/browser'>;
}
declare module 'react-document-title/test/common.js' {
  declare module.exports: $Exports<'react-document-title/test/common'>;
}
