// flow-typed signature: ebe70ecabce0cb69017cf9127f23e7d1
// flow-typed version: <<STUB>>/react-intersection-observer_v6.1.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intersection-observer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intersection-observer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-intersection-observer/dist/react-intersection-observer.cjs' {
  declare module.exports: any;
}

declare module 'react-intersection-observer/dist/react-intersection-observer.esm' {
  declare module.exports: any;
}

declare module 'react-intersection-observer/dist/react-intersection-observer.umd' {
  declare module.exports: any;
}

declare module 'react-intersection-observer/dist/react-intersection-observer.umd.min' {
  declare module.exports: any;
}

declare module 'react-intersection-observer/src/index' {
  declare module.exports: any;
}

declare module 'react-intersection-observer/src/intersection' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-intersection-observer/dist/react-intersection-observer.cjs.js' {
  declare module.exports: $Exports<'react-intersection-observer/dist/react-intersection-observer.cjs'>;
}
declare module 'react-intersection-observer/dist/react-intersection-observer.esm.js' {
  declare module.exports: $Exports<'react-intersection-observer/dist/react-intersection-observer.esm'>;
}
declare module 'react-intersection-observer/dist/react-intersection-observer.umd.js' {
  declare module.exports: $Exports<'react-intersection-observer/dist/react-intersection-observer.umd'>;
}
declare module 'react-intersection-observer/dist/react-intersection-observer.umd.min.js' {
  declare module.exports: $Exports<'react-intersection-observer/dist/react-intersection-observer.umd.min'>;
}
declare module 'react-intersection-observer/src/index.js' {
  declare module.exports: $Exports<'react-intersection-observer/src/index'>;
}
declare module 'react-intersection-observer/src/intersection.js' {
  declare module.exports: $Exports<'react-intersection-observer/src/intersection'>;
}
