// flow-typed signature: 122b809d3ab7b72ee24ccfdfa75dd07d
// flow-typed version: <<STUB>>/relay-compiler-webpack-plugin_v^0.5.11/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'relay-compiler-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'relay-compiler-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'relay-compiler-webpack-plugin/dist/getFileFilter' {
  declare module.exports: any;
}

declare module 'relay-compiler-webpack-plugin/dist/getFilepathsFromGlob' {
  declare module.exports: any;
}

declare module 'relay-compiler-webpack-plugin/dist/getSchema' {
  declare module.exports: any;
}

declare module 'relay-compiler-webpack-plugin/dist/getWriter' {
  declare module.exports: any;
}

declare module 'relay-compiler-webpack-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'relay-compiler-webpack-plugin/src/getFileFilter' {
  declare module.exports: any;
}

declare module 'relay-compiler-webpack-plugin/src/getFilepathsFromGlob' {
  declare module.exports: any;
}

declare module 'relay-compiler-webpack-plugin/src/getSchema' {
  declare module.exports: any;
}

declare module 'relay-compiler-webpack-plugin/src/getWriter' {
  declare module.exports: any;
}

declare module 'relay-compiler-webpack-plugin/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'relay-compiler-webpack-plugin/dist/getFileFilter.js' {
  declare module.exports: $Exports<'relay-compiler-webpack-plugin/dist/getFileFilter'>;
}
declare module 'relay-compiler-webpack-plugin/dist/getFilepathsFromGlob.js' {
  declare module.exports: $Exports<'relay-compiler-webpack-plugin/dist/getFilepathsFromGlob'>;
}
declare module 'relay-compiler-webpack-plugin/dist/getSchema.js' {
  declare module.exports: $Exports<'relay-compiler-webpack-plugin/dist/getSchema'>;
}
declare module 'relay-compiler-webpack-plugin/dist/getWriter.js' {
  declare module.exports: $Exports<'relay-compiler-webpack-plugin/dist/getWriter'>;
}
declare module 'relay-compiler-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'relay-compiler-webpack-plugin/dist/index'>;
}
declare module 'relay-compiler-webpack-plugin/src/getFileFilter.js' {
  declare module.exports: $Exports<'relay-compiler-webpack-plugin/src/getFileFilter'>;
}
declare module 'relay-compiler-webpack-plugin/src/getFilepathsFromGlob.js' {
  declare module.exports: $Exports<'relay-compiler-webpack-plugin/src/getFilepathsFromGlob'>;
}
declare module 'relay-compiler-webpack-plugin/src/getSchema.js' {
  declare module.exports: $Exports<'relay-compiler-webpack-plugin/src/getSchema'>;
}
declare module 'relay-compiler-webpack-plugin/src/getWriter.js' {
  declare module.exports: $Exports<'relay-compiler-webpack-plugin/src/getWriter'>;
}
declare module 'relay-compiler-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'relay-compiler-webpack-plugin/src/index'>;
}
