// flow-typed signature: 8df713b79270468dcfa23c4e89983ee9
// flow-typed version: <<STUB>>/search-query-parser_v^1.3.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'search-query-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'search-query-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'search-query-parser/lib/search-query-parser' {
  declare module.exports: any;
}

declare module 'search-query-parser/test/mocha' {
  declare module.exports: any;
}

declare module 'search-query-parser/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'search-query-parser/index' {
  declare module.exports: $Exports<'search-query-parser'>;
}
declare module 'search-query-parser/index.js' {
  declare module.exports: $Exports<'search-query-parser'>;
}
declare module 'search-query-parser/lib/search-query-parser.js' {
  declare module.exports: $Exports<'search-query-parser/lib/search-query-parser'>;
}
declare module 'search-query-parser/test/mocha.js' {
  declare module.exports: $Exports<'search-query-parser/test/mocha'>;
}
declare module 'search-query-parser/test/test.js' {
  declare module.exports: $Exports<'search-query-parser/test/test'>;
}
