// flow-typed signature: 99ecddf75a436fb6852726ac210aa927
// flow-typed version: <<STUB>>/shuffle-array_v1.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shuffle-array'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shuffle-array' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shuffle-array/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'shuffle-array/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shuffle-array/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'shuffle-array/coverage/lcov-report/prettify'>;
}
declare module 'shuffle-array/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'shuffle-array/coverage/lcov-report/sorter'>;
}
declare module 'shuffle-array/index' {
  declare module.exports: $Exports<'shuffle-array'>;
}
declare module 'shuffle-array/index.js' {
  declare module.exports: $Exports<'shuffle-array'>;
}
