// flow-typed signature: 2e88142401306c2d26ae0f263f205ad3
// flow-typed version: <<STUB>>/stats-webpack-plugin_v^0.6.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stats-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stats-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stats-webpack-plugin/index' {
  declare module.exports: $Exports<'stats-webpack-plugin'>;
}
declare module 'stats-webpack-plugin/index.js' {
  declare module.exports: $Exports<'stats-webpack-plugin'>;
}
