// flow-typed signature: 82ec8920bb3d49094f048a9f786c2a09
// flow-typed version: <<STUB>>/styled-transition-group_v^1.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-transition-group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-transition-group' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-transition-group/dist/bundle.es' {
  declare module.exports: any;
}

declare module 'styled-transition-group/dist/bundle' {
  declare module.exports: any;
}

declare module 'styled-transition-group/rollup.config' {
  declare module.exports: any;
}

declare module 'styled-transition-group/src/AnimatedComponent/index' {
  declare module.exports: any;
}

declare module 'styled-transition-group/src/AnimatedComponent/props' {
  declare module.exports: any;
}

declare module 'styled-transition-group/src/construct/css' {
  declare module.exports: any;
}

declare module 'styled-transition-group/src/construct/index' {
  declare module.exports: any;
}

declare module 'styled-transition-group/src/index' {
  declare module.exports: any;
}

declare module 'styled-transition-group/src/states' {
  declare module.exports: any;
}

declare module 'styled-transition-group/test/setup' {
  declare module.exports: any;
}

declare module 'styled-transition-group/test/transition.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-transition-group/dist/bundle.es.js' {
  declare module.exports: $Exports<'styled-transition-group/dist/bundle.es'>;
}
declare module 'styled-transition-group/dist/bundle.js' {
  declare module.exports: $Exports<'styled-transition-group/dist/bundle'>;
}
declare module 'styled-transition-group/rollup.config.js' {
  declare module.exports: $Exports<'styled-transition-group/rollup.config'>;
}
declare module 'styled-transition-group/src/AnimatedComponent/index.jsx' {
  declare module.exports: $Exports<'styled-transition-group/src/AnimatedComponent/index'>;
}
declare module 'styled-transition-group/src/AnimatedComponent/props.js' {
  declare module.exports: $Exports<'styled-transition-group/src/AnimatedComponent/props'>;
}
declare module 'styled-transition-group/src/construct/css.js' {
  declare module.exports: $Exports<'styled-transition-group/src/construct/css'>;
}
declare module 'styled-transition-group/src/construct/index.js' {
  declare module.exports: $Exports<'styled-transition-group/src/construct/index'>;
}
declare module 'styled-transition-group/src/index.js' {
  declare module.exports: $Exports<'styled-transition-group/src/index'>;
}
declare module 'styled-transition-group/src/states.js' {
  declare module.exports: $Exports<'styled-transition-group/src/states'>;
}
declare module 'styled-transition-group/test/setup.js' {
  declare module.exports: $Exports<'styled-transition-group/test/setup'>;
}
declare module 'styled-transition-group/test/transition.spec.jsx' {
  declare module.exports: $Exports<'styled-transition-group/test/transition.spec'>;
}
