// flow-typed signature: 60a102313b61646683596cddbfbf5ea6
// flow-typed version: <<STUB>>/throttleit_v^1.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'throttleit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'throttleit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'throttleit/example' {
  declare module.exports: any;
}

declare module 'throttleit/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'throttleit/example.js' {
  declare module.exports: $Exports<'throttleit/example'>;
}
declare module 'throttleit/index' {
  declare module.exports: $Exports<'throttleit'>;
}
declare module 'throttleit/index.js' {
  declare module.exports: $Exports<'throttleit'>;
}
declare module 'throttleit/test.js' {
  declare module.exports: $Exports<'throttleit/test'>;
}
