// flow-typed signature: 624f7135f2a1119374586239aac5b389
// flow-typed version: <<STUB>>/word-wrap_v1.2.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'word-wrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'word-wrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'word-wrap/index' {
  declare module.exports: $Exports<'word-wrap'>;
}
declare module 'word-wrap/index.js' {
  declare module.exports: $Exports<'word-wrap'>;
}
