env:
  FRONTEND_HOST: https://buildkiteassets.com/frontend/
  EMOJI_HOST: https://buildkiteassets.com/emojis
  S3_URL: s3://buildkiteassets.com/frontend/

steps:
  - group: "Setup"
    steps:
      - name: ":docker: Build Docker Image"
        plugins:
          docker-compose#v2.5.1:
            build: frontend
            image-repository: index.docker.io/buildkiteci/frontend
        env:
          RAILS_ENV: test
        agents:
          queue: elastic-builders

  - wait

  - group: "Test"
    steps:
      - name: ":eslint: ESlint"
        command: ".buildkite/steps/eslint.sh"
        plugins:
          docker-compose#v2.5.1:
            run: frontend

      - name: ":flowtype: Flow"
        command: ".buildkite/steps/flow.sh"
        plugins:
          docker-compose#v2.5.1:
            run: frontend

      - name: ":jest: Jest"
        command: ".buildkite/steps/jest.sh"
        artifact_paths: "coverage/*"
        plugins:
          docker-compose#v2.5.1:
            run: frontend

  - group: "Build"
    steps:
      - name: ":webpack: Webpack"
        command: ".buildkite/steps/webpack.sh"
        artifact_paths:
          - "bundle-analysis/*"
          - "dist/*"
        plugins:
          docker-compose#v2.5.1:
            run: frontend
